## makeCacheMatrix - Creates a special matrix 
##                    and caches its inverse
##
## cacheSolve - Returns an inverse of the matrix
##              if it already exists in the cache
##              and the object remains unchanged.
##              Else, it calculates
##              the inverse on the matrix returned
##              by makeCacheMatrix

## Receives a special matrix and caches the inverse
## and stores it in the global environment
makeCacheMatrix <- function(x = matrix()) {
  ##initialize the inverse matrix
  invMatrix <- NULL
  
  #define the set function for the matrix
  set <- function(y) {
    x <<- y
    invMatrix <<- NULL
  }
  
  ##define the return matrix object
  get <- function() {
    x ##return special matrix
  }
  
  ##setting the inverse matrix 
  setInvMatrix <- function(invM){
    invMatrix <<- invM ##assign the inverse matrix to the environment var
  } 
  
  ##define the function for returning the inverse matrix
  getInvMatrix <- function(){
    invMatrix ##the environment var inverse matrix is return
  }
  
  ##put all defined function into a list for a future call
  list(set = set,
       get = get,
       setInvMatrix = setInvMatrix,
       getInvMatrix = getInvMatrix)
}


## Returns an inverse of the matrix if it already exists in the cache
## and the object remains unchanged. Else, it calculates the inverse
## on the matrix returned by makeCacheMatrix
cacheSolve <- function(x, ...) {
  ## 1. - get the available inverse of the original matrix generated by makeCacheMatrix
  invM <- x$getInvMatrix()
  
  ## 2. Verify if the inverse has already been calculated
  if (!is.null(invM)){
    ## check if the return invMatrix is identical
    if ( identical( x$get() %*% invM, invM %*% x$get() ) ){
      ## get it from the cache and skip the computation. 
      print("getting cached data")
      return(invM)
    }
  }
  
  ## 3. Else inverse matrix null or matrix change, calculates the inverse 
  data <- x$get()
  invM <- solve(data, ...)
  
  # sets the value of the inverse in the cache via the setInv function.
  x$setInvMatrix(invM)
  
  ## Return a matrix that is the inverse of 'x'
  print("getting new computated data")
  return(invM)
}